#!/bin/bash

# dep ver
go_test_ver=v1.6.0
go_mod_tags_ver=v1.16.0
impl_ver=v1.1.0
go_play_ver=v1.0.0
delve_ver=latest
staticcheck_ver=latest
go_pls=latest

# deps
deps=(
  "github.com/cweill/gotests/gotests@${go_test_ver}"
  "github.com/fatih/gomodifytags@${go_mod_tags_ver}"
  "github.com/josharian/impl@${impl_ver}"
  "github.com/haya14busa/goplay/cmd/goplay@${go_play_ver}"
  "github.com/go-delve/delve/cmd/dlv@${delve_ver}"
  "honnef.co/go/tools/cmd/staticcheck@${staticcheck_ver}"
  "golang.org/x/tools/gopls@${go_pls}"
)

for i in ${deps[@]}; do
  go install ${i}
done

exit $?
